version: '3.3'

services:
  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888
  kafka1:
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zoo1
  mongo:
    image: 'mongo'
    container_name: mongo
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  config-server:
    image: "shynggys/com.example.config-server:latest"
    ports:
    - "8888:8888"
  eureka-server:
    image: "shynggys/com.example.eureka-server:latest"
    depends_on:
      - config-server
    ports:
    - "8761:8761"
    links:
      - config-server
  admin-server:
    image: "shynggys/com.example.admin-server:latest"
    depends_on:
      - config-server
    ports:
      - "12345:12345"
    links:
      - config-server
  gateway:
    image: "shynggys/com.example.gateway:latest"
    depends_on:
      - config-server
    ports:
      - "8080:8080"
    links:
      - config-server
      - redis
      - mongo

  message-process-service:
    image: "shynggys/com.example.message-process-service:latest"
    depends_on:
      - config-server
    environment:
      - INSTANCE_PORT=56984
    ports:
      - "56984:56984"
    links:
      - config-server
      - kafka1
      - mongo
      - redis
  message-process-service1:
    image: "shynggys/com.example.message-process-service:latest"
    depends_on:
      - config-server
    environment:
      - INSTANCE_PORT=56985
    ports:
      - "56985:56985"
    links:
      - config-server
      - kafka1
      - mongo
      - redis
  message-delivery-service:
    image: "shynggys/com.example.message-delivery-service:latest"
    depends_on:
      - config-server
    environment:
      - INSTANCE_PORT=45612
    ports:
      - "45612:45612"
    links:
      - config-server
      - kafka1
      - mongo
      - redis
  message-delivery-service2:
    image: "shynggys/com.example.message-delivery-service:latest"
    depends_on:
      - config-server
    environment:
      - INSTANCE_PORT=45613
    ports:
      - "45613:45613"
    links:
      - config-server
      - kafka1
      - mongo
      - redis
  message-delivery-service3:
    image: "shynggys/com.example.message-delivery-service:latest"
    depends_on:
      - config-server
    environment:
      - INSTANCE_PORT=45613
    ports:
      - "45613:45613"
    links:
      - config-server
      - kafka1
      - mongo
      - redis